name: CI/CD Backend - Cloud Run

on:
  push:
    branches:
      - qa
      - main
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

  workflow_dispatch:

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'production' || 'qa' }}

    concurrency:
      group: backend-${{ github.ref_name }}
      cancel-in-progress: true

    permissions:
      contents: read

    steps:
      - name: Mostrar ambiente
        run: |
          echo "Rama: ${{ github.ref_name }}"
          echo "Ambiente: ${{ github.ref_name == 'main' && 'PRODUCCIÓN' || 'QA' }}"

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Instalar dependencias
        working-directory: backend
        run: npm ci

      - name: Compilar backend
        working-directory: backend
        run: npm run build

      - name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Desplegar backend QA
        if: github.ref_name == 'qa'
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: cicd-backend-qa
          region: us-central1
          source: ./backend
          flags: >-
            --allow-unauthenticated
            --set-env-vars=APP_ENV=qa

      - name: Desplegar backend Producción
        if: github.ref_name == 'main'
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: cicd-backend-prod
          region: us-central1
          source: ./backend
          flags: >-
            --allow-unauthenticated
            --set-env-vars=APP_ENV=production